# encoding: utf-8
class AddPeople < ActiveRecord::Migration
  def self.up
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1000,'Ainkidu Arnimane','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1001,'Alex Collison Cooby','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1002,'Alex Nicoll Sweet','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1003,'Alex Preskot','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1004,'Anjo Sem Esperacca','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1005,'Antonia Lewis','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1006,'Aramina Larinth','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1007,'Artuš Pendragon','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1008,'Boris Grishenko','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1009,'Ceorge Newman','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1010,'Diotima Marlow','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1011,'Ema Teresa Fleming','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1012,'Emma Stay','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1013,'Gabriel Eruner','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1014,'Hildegarda Létavá','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1015,'Insidnie Hopkírková','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1016,'Isabell Caitlin Liteas','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1017,'Jeremy Auster','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1018,'Jessica Wiless','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1019,'Josefine dUfour','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1020,'Kat Thurst','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1021,'Kattarin Kilahimová','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1022,'Křídlatka Podivná','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1023,'Leila Jane Woods','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1024,'Lily Anne Lywesová','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1025,'Magnólia Lecter','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1026,'Marvarick Vápenon','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1027,'Matt Alcarmo','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1028,'Maxmilian Lucius Galton','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1029,'Melinda Westwoodová','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1030,'Morgana Pepper','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1031,'Nica Vlasta Bread','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1032,'Nina Luna Brilla','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1033,'Olivia Orsay Lacter','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1034,'Rebeca Santanová','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1035,'Rebecka Alice Black','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1036,'Rosalie Angel Sadness','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1037,'Rosemarie Dobrevová','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1038,'Samaryen Lie Elensar','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1039,'Sazie Cassidy','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1040,'Scallion October','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1041,'Scott Julius Stirling','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1042,'Suirou Tsuchimi','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1043,'Tina Lily Anessová','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1044,'Tom Jack Hedley','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1045,'Yvaine Jane Halliwell','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1046,'Anne Katrin Monmar','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1047,'Brianag Mac Coileáin','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1048,'Caitlin Galbraith','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1049,'Connie Clerenc','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1050,'Dahlia Athara','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1051,'Evelina van Eyck','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1052,'Justin Tj Hawk','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1053,'Lucy di Vampire','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1054,'Petronie Smith','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1055,'Scorpia DeadAngel','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1056,'Yasmin Mia Madisson','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1057,'Adretea Lyria','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1058,'Caroline the Unicorn','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1059,'Justin Angel Sane','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1060,'Katelyn Auster','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1061,'William O Farrell','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1062,'Cassiopeia Sagitta','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1063,'Elisa de Lunne','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1064,'Emma Violet Wang','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1065,'Estrele Večerníčková','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1066,'Leelee z Arkony','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1067,'Linn Rose Lairová','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1068,'Madeline the Unicorn','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1069,'Nicolette Marique Leroy','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1070,'Theresa Leagwitová','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1071,'ashley tie','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1072,'Elanius Aine Neil','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1073,'Ettariel Elvea','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1074,'Isabella Anne Swan','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1075,'James Watfar','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1076,'Lilien Emity Meissed','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1077,'Madidess Leevian','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1078,'Melánie Hale','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1079,'Thasa Monke Kemanová','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1080,'Larrie Larstonová','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1081,'David Lopez','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1082,'Katherine Angel','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1083,'Monny von Schatz','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1084,'Arien Rellyová','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1085,'Jacob Freezer','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1086,'Kathie Amanda Nakimur','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1087,'Phillipa O Connel','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1088,'Queti Sylie','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1089,'Ráďa Romanoff','Ravenclaw');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1090,'Abigail Cissy Roberts','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1091,'Amálie Žíhaná','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1092,'Amy Stragee','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1093,'Angela Richmond','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1094,'Ann Girendel','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1095,'Asi Sofia Stargesová','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1096,'Bakys de Lafehr','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1097,'Beatrice la Dolce','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1098,'Belinka Ellova','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1099,'Bike Sharius','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1100,'Calleb Mandrake','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1101,'Carol de Fila','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1102,'Carolin Eva Bardotová','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1103,'Ciline Flameová','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1104,'Coldery Icereen','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1105,'Dominique Rosembloom','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1106,'Elen Jenkinsová','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1107,'Ella Le Fletcher','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1108,'Ella z Frelu','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1109,'Elleron Linpé','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1110,'Emily Moonová','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1111,'Erin Ponožtičková','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1112,'Erumocio Thér','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1113,'Ewelyn Freaková','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1114,'Freya Carol Masonová','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1115,'Fritjof Skarpsvärd','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1116,'Gregor Sodorovicz','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1117,'Hedvige de lange','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1118,'Cherrolein Karamelka Scharly','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1119,'Isabella Lucy Summers','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1120,'Jaime Crump','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1121,'Larry Folkesson','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1122,'Leon Křiklavý','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1123,'Lilian Isabella Rorrs','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1124,'Mary Joanne Rodriguez','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1125,'Mindy Carson','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1126,'Palačinka Med Džemová','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1127,'Percival McDonald','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1128,'Phoenix Drake','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1129,'Rujana Pišpírková','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1130,'Samantha Am Chainless','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1131,'Sarah Rich','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1132,'Sophie De Lilian','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1133,'Stigie Dee Tompkins','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1134,'Susan Cooková','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1135,'Teresia Soapmaker','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1136,'terka slezáková','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1137,'Turmawen Handová','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1138,'Vanessa de Moor','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1139,'Dimin Dragondead','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1140,'Emma Smithová','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1141,'Esperanza Luisana Morgan','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1142,'Jane Karen Langley','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1143,'Lusia Fiona Crossová','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1144,'Magrápa Česneková','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1145,'Nicol Nash Orchidis','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1146,'Rosalie Ellen Bradshawová','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1147,'Rose Arnea Seize','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1148,'Safira Jane Bardotová','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1149,'Samantha Ulvenová','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1150,'Serafína Loxová','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1151,'Silvia Slimáková','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1152,'Smajlík Smoulík','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1153,'Zlatuška Gollumková','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1154,'Charlotte Von Emotion','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1155,'Chiara Cheisseová','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1156,'Kim Sarah Reevesová','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1157,'Vivianna Digal','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1158,'Adriana Bella Lee','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1159,'Alanise Olien Harlin','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1160,'Jostein Lauierová','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1161,'Natalie Davis','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1162,'Paul Brewer','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1163,'Teodorik Valdorius','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1164,'Vicky Charmant','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1165,'Ellka Willowa','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1166,'Pauline Elanorová','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1167,'Santara Aredhel Merenvenová','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1168,'Lucy Koralka','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1169,'Magica per Voluptas','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1170,'Myška de Krysa','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1171,'Piper Jarwealth','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1172,'Sophia Glis Glisová','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1173,'Siny de Sorrow','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1174,'Ywa od Roztodivných','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1175,'Felicitas Frobisherová','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1176,'Herwen Indil Eruvea','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1177,'Ines Dolfin','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1178,'Marylin Cuthbert','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1179,'Nicholas McElen','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1180,'Oresta Vianueva','Hufflepuff');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1181,'Abigail Sparkle','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1182,'Alcarinque Faile Lombres','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1183,'Alexandr Foxtrott','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1184,'Anabel von Waldorf','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1185,'Angelina Woodová','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1186,'Anna Helsingová','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1187,'Annie Claire Reff','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1188,'Anny Phoenix','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1189,'Ardhess Ayen','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1190,'Ashley Vipera Norrell','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1191,'Babsi Julie Lovestone','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1192,'Bobbie Jaya Lovestone','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1193,'Caledonia Delphini','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1194,'casey cox','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1195,'Catherine Hayle','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1196,'Claude Klein','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1197,'David Williams','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1198,'Diane Anne Lear','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1199,'Dominis Diamond Claynová','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1200,'Elis Jane Boneová','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1201,'Elizabeth Anne Groats','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1202,'Emily Smith','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1203,'Jessamine Keats','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1204,'John Fon Von','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1205,'John Ryan Krämmer','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1206,'Kate Craenová','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1207,'Katie Amstrdonova','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1208,'Katie Jane Panks','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1209,'Kirsten Woodová','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1210,'Larissa Jackesová','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1211,'Lucinda Goringová','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1212,'Marek Eliot','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1213,'Margit Claire Leeová','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1214,'Marion de Fell','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1215,'Menolly Larianeth','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1216,'Mia Scream','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1217,'Michael Picket','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1218,'Morwen Elizabeth Dragomirová','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1219,'Nerys Heliabel Ghostfieldová','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1220,'Nilis Listy','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1221,'Nina Caliente','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1222,'Oliwia Qen Twing','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1223,'Perceus Leade Lee','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1224,'PuFFlíík malá','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1225,'Samantha Lynn Thomas','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1226,'tulísek dolphinová','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1227,'Ustad Grande Herbe','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1228,'Veronique Milagrosa','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1229,'Victoria Cutteridge','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1230,'Viviana Morgan','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1231,'Alex Rattray','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1232,'Bree Tanner','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1233,'Cathrine Lokwood','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1234,'Dermil Akeldur Aksis','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1235,'Dors Venabili','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1236,'Innela Craenová','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1237,'Karin Axe Brownová','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1238,'Keaty Fox Darksová','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1239,'Kouhei Hasangeki','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1240,'Leroy Marshová','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1241,'Sarah Callens','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1242,'Tamarka Pudlíčková','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1243,'Alissia Catherine Alterey','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1244,'Angelica Arless','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1245,'Briseis Kouzelná','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1246,'Helene Langdon','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1247,'Horacio de Sunlock','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1248,'Jessica Brownová','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1249,'Michelle Pobertová','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1250,'Nicol Rodrigez','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1251,'Sheila Lostris','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1252,'Elbereth Gilthoniel','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1253,'Jassem Rinal','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1254,'Mariana Kohoutová','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1255,'Tartufa von Tarkin','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1256,'Yenyfer Earth','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1257,'Ignacius Horak','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1258,'Jane Mooren','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1259,'Jane Patricia Vamos','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1260,'Lenka Michaleová','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1261,'Mark Petersvood','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1262,'Meredith Jade Hogan','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1263,'Nebelbrach Mechacha','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1264,'Niane z Libelusie','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1265,'Esperanza Milagrosa','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1266,'Mathiel Sophia','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1267,'Peter Sviter','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1268,'Aváček de Hillson','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1269,'Kate Resea','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1270,'Rebecca Shadowfang','Gryffindor');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1271,'Aischa Nassib','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1272,'Alexandra Petrova','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1273,'Amaya Claire Incantatrice','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1274,'Amiga Atari','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1275,'Angel Catherine Zvonová','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1276,'Angie Fayhoodová','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1277,'Annie Elisabeth Cheeky','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1278,'Annie Park Slimová','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1279,'Any Rayová','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1280,'Archibald O Neill','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1281,'Arwen van Weverstraat','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1282,'Astoria Eleanore Serpens','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1283,'Ašiga ze Zliče','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1284,'Cassandra Aurora Nott','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1285,'Ceana Logen','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1286,'Cia Papanctek','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1287,'Erich Černodymov','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1288,'Evelin Sweetová','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1289,'Georgina Blair Eastwick','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1290,'Giuseppe Johnson','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1291,'Hay Lineová','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1292,'Helen Berlioz Dardania','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1293,'Hugh Snakers','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1294,'Christina Étoiles','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1295,'Issa de Phalaenae','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1296,'Jackelin Mandragor','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1297,'Kate Sarah Black','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1298,'Katherine Elis Redbirdová','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1299,'Kostěj Zimolez Měsíčník','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1300,'Leonidas Thermopylus','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1301,'Leslee J Smithersová','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1302,'Lucas Season Smith','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1303,'Lucia New','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1304,'Maff Korebel','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1305,'Maxmilian Addams','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1306,'NaSaŠí Jackson','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1307,'Ofélily Freistein','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1308,'Padric McConway','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1309,'Partimus Angelisimus','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1310,'Poppy Moore','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1311,'Rezinho Badalandabad','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1312,'Rosalie McDrower','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1313,'Samish McKelly','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1314,'Sarah Elleanor Mortier','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1315,'Sassy Venedetta','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1316,'Shane Manson','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1317,'sisi rosiaková','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1318,'Sorina Pane','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1319,'Sue Carvins','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1320,'Terix Morieng','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1321,'Verity Heather Atherton','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1322,'Amelie Green Rorrs','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1323,'Cindy Miss','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1324,'Kate Jordon','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1325,'Kristie Smithová','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1326,'Minamino Shana','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1327,'Osiris Flemingová','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1328,'Ralf Henrik','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1329,'Sineph Gnohov','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1330,'Aerith Rigel','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1331,'AnnaLynne Patrisha Simons','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1332,'Henrik Leens','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1333,'Jaňulka Wirvalová','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1334,'Kargowan Aster','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1335,'Elizabeth Lextrová','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1336,'Irma Von Feenwald','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1337,'Lucy de Lioncourt','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1338,'Marissa Alvarado Risa','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1339,'Barbara Arianne Lecter','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1340,'Carolina Rebecca Pinc','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1341,'Ginevra de Naga','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1342,'Lili Smeaglová','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1343,'Thorhall Ranucull','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1344,'Cerridwen Lowra Antares','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1345,'Jadis Ssss Slytherin','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1346,'Merrisa Newman','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1347,'Wenai Lafayette','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1348,'Elanis Aelana Roselfová','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1349,'Riannon Evansova','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1350,'Tydynka Flyová','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1351,'Adanedhel Bloom','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1352,'Alcielle Alcine Elenie','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1353,'Anna Maria Salomeová','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1354,'Gita Hrdličková','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1355,'Jean Molliacová','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1356,'Lucira de Radimaru','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1357,'Marguerita Laux','Slytherin');"
    execute "INSERT INTO `people` (`id`, `name`, `house`) VALUES (1358,'Sarah Elliotová','Slytherin');"

  end

  def self.down
    execute "DELETE FROM users WHERE id between 1000 and 1358"
  end
end
